### ISSUE TITLE
Incorrect Maven setting in the FARACON Developer Guide

### ISSUE THREAD

**Issue by jhflow** [GENIVI/franca_ara_tools#108]
In the FARACON Developer Guide (https://github.com/GENIVI/franca_ara_tools/wiki/FARACON-Developer-Guide), I found an incorrect Maven setting on "3. Configure Artop access":

```
...
	<servers>
		<server>
			<id>https://www.artop.org/containers/artop-sdk-update-site-4.12</id>
			<username>YOUR_ARTOP_USERNAME</username>
			<password>YOUR_ARTOP_PASSWORD</password>
		</server>
	</servers>
...
```

The value of <id> should be "artop" instead of the full URI since the "id" of the repository is set as follows:

```
// releng/org.genivi.faracon.target/fara-oxygen-artop.target
...
50:      <repository id="artop" location="https://www.artop.org/containers/artop-sdk-update-site-4.12"/>
...
```

**Comment by MLanghammer** [comment]
Hi, 
Thanks a lot for the hint. 
We forgot to update it in the guide. We did that now. 
Best,
Michael
