### ISSUE TITLE
CLI interface wrong for Autosar->fild conversion

### ISSUE THREAD

**Issue by Anzey** [GENIVI/franca_ara_tools#114]
Diff attached.
[diff.txt](https://github.com/GENIVI/franca_ara_tools/files/3646726/diff.txt)

**Comment by MLanghammer** [comment]
Hi, 
you are right. We this with with the upcoming release.
Thanks a lot.
Best,
Michael

**Comment by MLanghammer** [comment]
Hi, 
this is fixed with Release 0.9. If it is not working please let us know. I will close the ticket for know.
Thanks for your help.
Best,
Michael
