### ISSUE TITLE
Problem with build under Linux

### ISSUE THREAD

**Issue by Anzey** [GENIVI/franca_ara_tools#115]
Diff attached.
[diff.txt](https://github.com/GENIVI/franca_ara_tools/files/3646791/diff.txt)

**Comment by MLanghammer** [comment]
Hi, thanks for the hint, we fix this in the upcoming release.

**Comment by MLanghammer** [comment]
Hi, 
with Release 0.9, this should be fixed (all tests are working now under windows and Linux). 
If not, please let us know and we reopen the issue :)
Thanks again.
Best,
Michael
