### ISSUE TITLE
Query regarding Franca_ara_tools

### ISSUE THREAD

**Issue by Siddharthav1** [GENIVI/franca_ara_tools#154]
I have read about the faracon tool. I am trying to use it to know how does it work. I referred https://www.autosar.org/fileadmin/user_upload/standards/classic/4-3/AUTOSAR_TR_FrancaIntegration.pdf  document. 

Here my question is:
1. Do franca connector files are handwritten or auto generated from the faracon tool?
2. Is there any way to work with the Faracon tool without accessing to the artop website?
3. Can I get any example so that I can refer and get the feeling that is how the franca_ara_tool works?

Any suggestion will help me a lot.

Regards,
Siddhartha V

**Comment by kbirken** [comment]
The AUTOSAR technical report you are referencing above has been published some years ago, when AUTOSAR Adaptive didn't exist yet. It describes how to map AUTOSAR _Classic_ to Franca and vice versa. As AUTOSAR Classic and Franca interfaces do not map 1:1 conceptually, a separate Connector DSL has been defined which provides the missing link between these two. This TR was done by a working group consisting of members from AUTOSAR and GENIVI.

There is an implementation of the TR, done mostly be Fraunhofer Berlin. This model-to-model transformation tooling was called _IoNAS_. As this uses AUTOSAR I.P., the transformation engine is hosted in an AUTOSAR subversion repository and is available only for AUTOSAR (development?) members. Additionally, there is a public repository named [IoNAS-hmi](https://github.com/GENIVI/ionas-hmi) which adds some Eclipse UI features for this transformation engine. Pls read the README of this repo to get more information.

Now some responses to your questions:

- ad (1): connector files are related the IoNAS tooling, which has nothing to do with the faracon tool
- ad (2): no, you need to have access to a repo hosted at artop.org, which is available only for AUTOSAR members
- ad (3): pls have a look at the README and the wiki of this repository (Franca_ara_tools)

**Comment by Siddharthav1** [comment]
Thank you sir for the response.
