### ISSUE TITLE
How to get field value in Stub

### ISSUE THREAD

**Issue by nekum109** [GENIVI/franca_ara_tools#170]
For getting field value which function we have to use in Stub.
which function will be invoked on Stub when Proxy requests current field value (get field value)

**Comment by kbirken** [comment]
This is the project for conversion of Franca files into Adaptive AUTOSAR and vice versa. You question seems to target some code generator? Pls. elaborate, so we can find out if is actually a question regarding the AUTOSAR transformation.

**Comment by nekum109** [comment]
I have one attribute in my fidl file  attribute sFields_GroupType fieldData 
In My fdepl file I had made its getter true please refer below code
attribute fieldData {
     SomeIpGetterID = 30003
     SomeIpGetterReliable = true
     SomeIpSetterID = 30004
     SomeIpSetterReliable = true
     SomeIpNotifierID = 30005
     SomeIpNotifierReliable = true
     SomeIpEventGroups = { 17746 }
   }
can you please let me know when the code will get generate from fidl and fdepl file which function can we use to check getFieldAttribute

**Comment by nekum109** [comment]
How does proxy  getFieldValue from stub below are the functions which are generated
COMMONAPI_EXPORT virtual void onRemoteFieldDataAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteFieldDataAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetFieldDataAttribute(::v1::stla::wrapper::Types::sFields_GroupType _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetFieldDataAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetFieldDataAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v1::stla::wrapper::Types::sFields_GroupType _value) {
            (void)_client;
            return onRemoteSetFieldDataAttribute(_value);
        }
in the above function which one can be used and how?

**Comment by kbirken** [comment]
This is a question about the CommonAPI-C++ code generator. The corresponding repo/project is this: https://github.com/COVESA/capicxx-core-tools

Pls. address the guys over there, I will close this ticket here as "won't fix".
