### ISSUE TITLE
F2A: Implement transformation aspects for Franca array data types

### ISSUE THREAD

**Issue by kbirken** [GENIVI/franca_ara_tools#37]
This issue handles the mapping from Franca array data types to AUTOSAR. Note that in Franca IDL arrays might be either defined as explicit (named) data type, or as implicit (unnamed) data item. The latter is invoked by setting the FTypedElement.array flag for a specific FTypedElement object.

This is part of **A100.2**.

**Comment by TorstenGoerg** [comment]
Encompasses the Franca features IDL1540, IDL1550, and IDL1620.
