### ISSUE TITLE
F2A: Implement transformation aspects for Franca's FTypeRef

### ISSUE THREAD

**Issue by kbirken** [GENIVI/franca_ara_tools#40]
FTypeRef elements in Franca can describe one of the following:
- predefined types
- user-defined types
- ranged integer types.

This issue handles the mapping of all three variants to proper constructs in arxml.

This is part of **A100.2**.

**Comment by TorstenGoerg** [comment]
Encompasses the Franca features IDL170, IDL1800, and IDL1810.
